name: GitHub Actions - C# Demo
on: [push]
jobs:
  run-csharp-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use secret in build
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: echo "La clé est $API_KEY"
      - name: Installer .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Lister les fichiers du dépôt
        run: ls -lsa
      - name: Compiler le programme C#
        run: dotnet build Devoir-Github_action_avec_csharp.csproj
      - name: Lancer le programme compilé
        run: dotnet run --project Devoir-Github_action_avec_csharp.csproj
