name: Vérification pull request
on: [pull_request]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Build
        run: dotnet build
      - name: Format check
        run: dotnet format --verify-no-changes #fait échouer le job si le code n’est pas bien formaté